language: php

dist: xenial
php:
  - "7.1"

env:
  - OXID=6.1
  - OXID=6.0

cache:
  directories:
  - $HOME/OXID
services: mysql

before_install:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - mysql -e 'CREATE DATABASE oxid;'

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - sh ./.travis.before_script.sh

script:
  - cd ~/OXID/
  - ./vendor/bin/runtests-coverage
  - php vendor/bin/codacycoverage --commit $TRAVIS_COMMIT clover ~/OXID/source/modules/oxcom/moduleinternals/Tests/reports/clover.xml

before_cache:
  - composer remove "oxid-community/moduleinternals"
  - rm -rf ~/OXID/source/modules/oxcom/moduleinternals
  - rm -rf ~/OXID/vendor/oxid-community/moduleinternals
  - rm -rf ~/OXID/source/tmp/*

