language: php

dist: xenial
php:
  - "7.1"

env: TRAVIS_ERROR_LEVEL=22519
cache:
  directories:
  - $HOME/OXID
services: mysql

before_install:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - mysql -e 'CREATE DATABASE oxid;'

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - sh ./.travis.before_script.sh
  
ignore:
  - apt-get install -y xfce4 xvfb x11vnc openjdk-7-jre-headless rng-tools 

script:
  - cd ~/OXID/
  - ./vendor/bin/runtests
  - vendor/bin/runtests-selenium

before_cache:
  - composer remove "oxid-community/moduleinternals"
  - rm -rfv ~/OXID/source/modules/oxcom/moduleinternals
  - rm -rfv ~/OXID/vendor/oxid-community/moduleinternals
  - rm -rfv ~/OXID/source/tmp/*

